DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS roles;
-- DROP TABLE IF EXISTS user_role;
--
-- CREATE TABLE users (
--     id       INT AUTO_INCREMENT PRIMARY KEY,
--     name     VARCHAR(250) NOT NULL,
--     password VARCHAR(250) NOT NULL
-- );
--
-- CREATE TABLE roles (
--     id   INT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(250) NOT NULL
-- );
--
-- CREATE TABLE user_role  (
--     user_id INT NOT NULL,
--     role_id INT NOT NULL
-- );

-- insert into roles (name) values ('ROLE_ADMIN');
-- insert into roles (name) values ('ROLE_USER');